server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: taobao-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liyingjie-97/taobao_config.git
          username: liyingjie-97
          password: Lyj970296011