server:
  port: 8002
spring:
  application:
    name: PRODUCT-PROVIDER
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip